name: flutter_facebook_signin
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auth_provider:
    git:
      url: git@github.com:solutelabs/dart_auth_provider.git
  flutter_facebook_login: ^3.0.0
  http: ^0.12.0+2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: